"""init

Revision ID: edb01f08b302
Revises: 
Create Date: 2022-05-11 16:39:48.528087

"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb01f08b302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(),
                              nullable=False),
                    sa.Column('role', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('e_queue',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('barber_id', sa.Integer(), nullable=False),
                    sa.Column('is_started', sa.Boolean(), nullable=False),
                    sa.Column('started_at', sa.DateTime(), nullable=True),
                    sa.Column('ended_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['barber_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_e_queue_id'), 'e_queue', ['id'], unique=True)
    op.create_table('feedback',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('barber_id', sa.Integer(), nullable=False),
                    sa.Column('rate', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['barber_id'], ['user.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=True)
    op.create_table('masters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('barber_id', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.Float(), server_default=sa.text(
                        '(0.0)'), nullable=True),
                    sa.Column('rate_count', sa.Integer(),
                              server_default=sa.text('0'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['barber_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_masters_id'), 'masters', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_masters_id'), table_name='masters')
    op.drop_table('masters')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_e_queue_id'), table_name='e_queue')
    op.drop_table('e_queue')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
